[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"

[font]

normal.family = "CaskaydiaMono NF"
bold.family = "CaskaydiaMono NF"
italic.family = "CaskaydiaMono NF"
bold_italic.family = "CaskaydiaMono NF"

size = 12.0
